### ISSUE TITLE
Allow mobanfile to include data from arbitrary config files

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#126]
Currently a mobanfile can only include one `overrides:` to list a yaml file which contains more settings.

In order to split input data into multiple files, the following is needed: A.yaml `overrides:` B.yaml `overrides:` C.yaml

However B and C may have unrelated set of data, so it is an annoyance that B should refer to C.

This also reduces re-usability.

Another project (Z) might want to use the values in B , but not the values in C.

A should be able to directly include B and C, while Z includes B only.

**Comment by jayvdb** [comment]
The other place where multiple yaml files could be introduces is the inner `configuration:` key.
i.e.
```yaml
configuration:
  template_dir:
    - "setupmobans:templates"
    - ".moban.d"
  configuration:
    moban.yml:
    other.yaml:
```

and

```yaml
targets:
  - output: CHANGELOG.rst
    template: CHANGELOG.rst.jj2
    configuration:
      changelog.yml:
      mobanfile:
```

The latter example could be used to remove the `name` and `organisation` keys in `changelog.yml` , which duplicate values in `mobanfile`.
