### ISSUE TITLE
Layered Jinja templates with the same name

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#17]
I must admit I am not sure this is a great idea...but IMO is worth discussing.

Currently it is not possible to have two templates with the same name.  That prevents a local one vs a global one.

One example:

1. local `.moban.dt/MANIFEST.in.jj2` with block 'more_options'
2. https://github.com/moremoban/pypi-mobans/blob/master/templates/MANIFEST.in.jj2

Another:

1. local `.moban.dt/setup.py.jj2` with blocks
2. https://github.com/moremoban/pypi-mobans/blob/master/templates/setup.py.jj2

That could be confusing, but then creating local templates with variant template names is also confusing, and annoying as they will have a common and unnecessary prefix.

**Comment by chfw** [comment]
django templating system has solved this problem. Let me check if jinja2 has anything similiar.

**Comment by chfw** [comment]
I got no luck with jinja2. The closest choice was [ChoiceLoader](https://github.com/pallets/jinja/blob/master/jinja2/loaders.py#L376) but it is clever enough to understand `setup.py.jj2` extends another `setup.py.jj2`, which locates in a different but sequential ordered folder.

The work around would be putting files under a special directory:

.moban.dt/local-override/setup.py.jj2

And then use this configuration{

```
configuration:
  configuration_dir: "commons/config"
  template_dir:
    - ".moban.dt"
    - "commons/templates"
    - "setupmobans/templates"
  configuration: your.yml
targets:
  - setup.py: local-override/setup.py.jj2
```

Well, technically, there could be one more choice is to implement such a overlapping template loader by extending jinja2's baseloader. However, this may take some unknown time.
