### ISSUE TITLE
Allow setting all Jinja env options

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#202]
sometimes the default jinja syntax is inappropriate.
Need option to set all options of the jinja env.
https://github.com/zyguan/textpl/blob/master/render.py

```yaml
targets:
  - output: foo
    template: foo.jj2
    options:
      ..
      block_end_string: '*))'
      ...
```

This could be used to add basic support for many template types.

**Comment by jayvdb** [comment]
@ayan-b, you want to try this one next?

**Comment by jayvdb** [comment]
e.g. https://github.com/moremoban/moban/issues/52 and https://github.com/moremoban/moban/issues/51 could be implemented with jinja options.

initially create a new engine when options are different.

We can have a separate issue about optimising by re-using engines with the same options.

**Comment by jayvdb** [comment]
(We could even use this instead of 'copy' by giving copy targets impossible jinja options, i.e. start/ends which never appear in any text.

**Comment by jayvdb** [comment]
P.s. yaml spec references can be used to avoid the options in the yaml being repetitive. There is no need to create a shorter syntax.

And the options attribute should be reusable for other template engines.

**Comment by chfw** [comment]
I support `options` and this will change the engine interface:

apply_template(..., options=None)

**Comment by ayan-b** [comment]
Assigning myself.

**Comment by ayan-b** [comment]
@chfw @jayvdb I think it is better if we move extensions within options, _i.e._, 
```
targets:
  - output: foo
    template: foo.jj2
    options:
      ..
      block_end_string: '*))'
      extensions: bar
      ...
```

**Comment by chfw** [comment]
Here is my further thought. This change here customizes the jinja2 env, resulting slight different jinja2 template engine behavior. An additional fancy feature will be required:

```
define:
  my_new_engine:  # create a reusable engine within this context
    - overrides: jinja2
    - options:
      ..
      block_end_string: '*))'
      ... 
targets
  - a.output: a.my_new_engine
  - output: b.output
    template: b.unknown
    template_type: my_new_engine
  - output: c.output  # this will create ad-hoc jinja2 engine, and get dumped after the op.
     template: c.alien
     template_type:
      - overrides: jinja2
      - options:
        ..
        block_end_string: '*))'
        ...
  - output: d.output
    template: d.unknown
    template_type: my_new_engine
```

In this way, the interface would be cleaner.

**Comment by ayan-b** [comment]
Got it!

**Comment by chfw** [comment]
This will touch the core of plugin engine. I can provide assistance while you code.

**Comment by jayvdb** [comment]
I think `define` should be `template_types`, and we should allow for the existing defaults of the jinja engine to be globally changed in the config.  i.e.

```yaml
template_types:
  jinja:
    file_extensions:
      - jj2
      - jj
      - xyz
    options:
      extensions:
        - do
  latexjj:
    overrides: jinja
    file_extensions:
      - texjj
    options:
      block_end_string: '*))'
      ...
  Nunjucks:  # https://github.com/moremoban/moban/issues/216
    overrides: jinja
    file_extensions:
      - njk
    options:
      ..
```

i.e. creating the following definitions
- An engine is a generic configurable tool.
- A template type is an engine with a set of options determining how it works.
- Each engine will usually have an implicit template type that has the same name, with defaults for all options

Also "overrides" is currently used for merging yaml mappings between files.  We need to be careful that we re-use that keyword in a consistent way - i.e. mappings only, never arrays.  So `file_extensions:` replaces any existing value in the data being overriden, because it is an array.

For many users/uses, they user will want one engine, with one set of options, and they want those options to apply to an existing set of file extensions which might be already mapped to an engine.  i.e. they want to change the template engine options, rather than create a new engine using more complicated yaml and it sounds more scary.

Also we should consider putting the new `define`/`template_types` keys under the existing top level `configuration:` , which already has `template_dir` sub key.  Any new top level key can conflict with user top level keys, and IMO should be prefixed with `moban_` to avoid such conflicts, like we had with `version`.

**Comment by chfw** [comment]
what about the following revised syntax:

```
configuration: # under configurations
  template_types:
    jinja:
      base_type: jinja2  # use base_type, instead of overrides
      file_extensions:
        - jj2
        - jj
        - xyz
      params:
        extensions:
          - do
    latexjj:
      base_type: jinja2
      file_extensions:
        - texjj
      params:
        options:
          block_end_string: '*))'
          ...
```

**Comment by jayvdb** [comment]
`base_type` is a good idea - avoiding re-use of `overrides` so it can have different semantics if necessary.

I dont yet see the benefit of having `params.options` - there should be one key under each template type, holding a mapping, and anything in the mapping goes to the engine.  `moban` shouldnt care what is under it.

`extensions` and `block_end_string` are both jinja settings, equally unknown to moban, so I think they should be at the same level.

We should probably do some modelling of the `params` / `options` / etc of another powerful engine, to help us see beyond jinja.

**Comment by ayan-b** [comment]
So, what syntax are we going to follow?

**Comment by chfw** [comment]
@jayvdb, what about:
```
configuration: # under configurations
  template_types:
    jinja:
      base_type: jinja2  # use base_type, instead of overrides
      file_extensions:
        - jj2
        - jj
        - xyz
      extensions:
        - do
    latexjj:
      base_type: jinja2
      file_extensions:
        - texjj
      options:
        block_end_string: '*))'
        ...
```

**Comment by jayvdb** [comment]
`extensions:` should be under `options:`.  It is a jinja-specific option.  The moban engine shouldnt need to know about it.  It just passes all options to the engine.

**Comment by chfw** [comment]
@ayan-b @jayvdb , I think the following syntax should be the consensus:

```
configuration: # under configurations
  template_types:
    jinja:
      base_type: jinja2  # use base_type, instead of overrides
      file_extensions:
        - jj2
        - jj
        - xyz
      options:
        extensions:
          - do
    latexjj:
      base_type: jinja2
      file_extensions:
        - texjj
      options:
        block_end_string: '*))'
        ...
```

**Comment by chfw** [comment]
don't forget that we have an additional syntax for ad-hoc(one-off) template engine instances:

```
targets
  - a.output: a.my_new_engine
  - output: b.output
    template: b.unknown
    template_type: my_new_engine
  - output: c.output  # this will create ad-hoc jinja2 engine, and get dumped after the op.
     template: c.alien
     template_type:
      - overrides: jinja2
      - options:
        ..
        block_end_string: '*))'
        ...
```

**Comment by chfw** [comment]
sorry, hereby I would like to clarify the ad hoc template type:

```
targets
  - a.output: a.my_new_engine
  - output: b.output
    template: b.unknown
    template_type: my_new_engine
  - output: c.output  # this will create ad-hoc jinja2 engine, and get dumped after the op.
     template: c.alien
     template_type:
        base_type: jinja2  # <-- no long it has '-' in the front
        options: # <-- no long it has '-' in the front
          ..
          block_end_string: '*))'
          ...
```

Hence, the syntax become the same as the `template_types` definition.
