### ISSUE TITLE
Custom jinja plugins

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#23]
Sort of related to https://github.com/moremoban/moban/issues/18 ..

while moban providing some extra built-in filters/tests might be helpful, it would be even more helpful if moban loaded filters/tests from the moban yaml configuration, and even loaded custom `globals` for greater convenience.

e.g.
```yaml
- plugin_dirs:
  - /path/to/.moban-py
- plugins:
  - jinja_globals:
    - load_file.py
  - jinja_filters:
    - strip_blank_lines.py
  - jinja_tests:
    - file_exists.py
```

where `.moban-py/file_exists.py` would provide the functionality needed for https://github.com/moremoban/moban/issues/18 , and

`.moban-py/load_file.py` and `.moban-py/strip_blank_lines.py`  would allow
```jinja2
{{ set var = load_file('foo') | strip_blank_lines }}
```
