### ISSUE TITLE
template_types: task 1: parse template_types

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#233]
The ability to parse the following syntax and retrieve a custom definition of template engine:

```
    jinja:
      base_type: jinja2  # use base_type, instead of overrides
      file_extensions:
        - jj2
        - jj
        - xyz
      options:
        extensions:
          - do
```

#202
