### ISSUE TITLE
template_types: task 2: expand the definition of template_type in targets section

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#234]
so that an ad-hoc instance of template engine will be created, used and dumped.

```
targets
  - a.output: a.my_new_engine
  - output: b.output
    template: b.unknown
    template_type: my_new_engine
  - output: c.output  # this will create ad-hoc jinja2 engine, and get dumped after the op.
     template: c.alien
     template_type:
      - overrides: jinja2
      - options:
        ..
        block_end_string: '*))'
        ...
```

#202
