### ISSUE TITLE
Add support for regex in mobanfile

### ISSUE THREAD

**Issue by ayan-b** [moremoban/moban#263]
Something like:
```yaml
targets:
  - resume/**.tex: **.tex_jj2
```
Maybe in configuration we can define `use_regex: True`
```yaml
configuration:
  use_regex: true
targets:
  - resume/**.tex: **.tex_jj2
```
