### ISSUE TITLE
Add pull request management

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#286]
Instead of using `requires` entry attribute `branch` , usually what we want is to refer to a pull request that is required.

i.e. instead of

```yaml
requires:
  - type: git
    url: https://github.com/jayvdb/pypi-mobans
    branch: setup-env-markers
```

we would use

```yaml
requires:
  - type: github
    url: https://github.com/moremobans/pypi-mobans
    pull_request_id: 92
```

The important distinction is that the `url` is then `https://github.com/moremobans/pypi-mobans` , not the fork, and therefore it doesnt need to change.  After the PR is merged, the line `pull_request_id: 92` can get dropped, no change to the other lines.

When the PR is merged, moban would then automatically switch back to using the default branch, with a warning that the pull request identifier is being ignored.

note `git` -> `github` is very optional, and would imply that `gitlab` is also needed, etc, etc.  Is it worth it??  It also doesnt help when 'bitbucket' might also need 'bitbucket-hg' if we ever get to hg support.

https://gitlab.com/gitmate/open-source/IGitt would be a useful wrapper, except that it only supports py3+.  However if we change all the `moban` jobs to py3.6 (coala already does this), this could be a py3+ only feature.
