### ISSUE TITLE
Allow template type per template

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#58]
Currently `template_type` can only appear at:

```yaml
configuration:
  template_type: ...
  ...
```

While that default is ok, it should be possible to override it per template.
e.g.
```
targets:
  - output: LICENSE
    template: license.mako
    template_type: mako
```

**Comment by chfw** [comment]
No the syntax will be like this:

```
targets:
  - LICENSE: license.mako
  - output: setup.py
    template: setup.py.mako
    configuration: config.yml
```

No changes to jinja based syntax.
